function renderAdminUsers() {
  const tbody = document.getElementById('admin-users-tbody'); if(!tbody) return;
  tbody.innerHTML = usuarios.map(u => { const setor = setores.find(s => s.id === u.setorId); const permissoes = setor ? setor.permissoes.join(', ') : 'Nenhuma'; return `<tr><td style="font-weight:500;">${u.nomeExibicao || u.nome}</td><td>${u.nome}</td><td>${setor?.nome || '—'}</td><td><span class="tag tag-blue">${permissoes}</span></td><td><button class="btn btn-secondary btn-sm" onclick="editUser(${u.id})">Editar</button> <button class="btn btn-danger btn-sm" onclick="deleteUser(${u.id})">Excluir</button></td></tr>`; }).join('');
}

function renderAdminSetores() {
  const tbody = document.getElementById('admin-setores-tbody');
  if (!tbody) return;
  if (!setores || setores.length === 0) {
    tbody.innerHTML = '<tr><td colspan="3" style="text-align:center; padding:40px;">Nenhum setor cadastrado</td></tr>';
    return;
  }
  tbody.innerHTML = setores.map(s => `
    <tr>
      <td style="font-weight:500;"><strong>${s.nome}</strong></td>
      <td><div style="display:flex;flex-wrap:wrap;gap:4px;">${s.permissoes.map(p => `<span class="tag tag-purple">${p}</span>`).join('')}</div></td>
      <td><button class="btn btn-secondary btn-sm" onclick="editSetor(${s.id})">Editar</button> <button class="btn btn-danger btn-sm" onclick="deleteSetor(${s.id})">Excluir</button></td>
    </tr>
  `).join('');
}

function carregarSetoresNoSelectPermissao() { const select = document.getElementById('perm-setor-select'); if(select) { select.innerHTML = setores.map(s => `<option value="${s.id}">${s.nome}</option>`).join(''); carregarPermissoesDoSetor(); } }
function carregarPermissoesDoSetor() { const setorId = parseInt(document.getElementById('perm-setor-select')?.value); if(!setorId) return; const setor = setores.find(s => s.id === setorId); if(!setor) return; const todasPermissoes = ['dashboard','kanban','processos','clientes','agenda','relatorios','admin','publicacoes']; document.getElementById('permissoes-checkboxes').innerHTML = todasPermissoes.map(perm => `<label class="perm-checkbox"><input type="checkbox" value="${perm}" ${setor.permissoes.includes(perm) ? 'checked' : ''}> ${perm}</label>`).join(''); }
function salvarPermissoesSetor() { const setorId = parseInt(document.getElementById('perm-setor-select').value); const setor = setores.find(s => s.id === setorId); if(setor) { const checkboxes = document.querySelectorAll('#permissoes-checkboxes input[type="checkbox"]'); const novasPermissoes = Array.from(checkboxes).filter(cb => cb.checked).map(cb => cb.value); setor.permissoes = novasPermissoes; renderAdminSetores(); renderAdminUsers(); showToast(`Permissões do setor ${setor.nome} atualizadas!`); salvarDados(); } }

let editingUserId = null;
function openNewUserModal() { editingUserId = null; document.getElementById('user-modal-title').innerText = 'Novo Usuário'; document.getElementById('user-nome').value = ''; document.getElementById('user-login').value = ''; document.getElementById('user-senha').value = ''; document.getElementById('user-iniciais').value = ''; document.getElementById('user-setor').innerHTML = setores.map(s => `<option value="${s.id}">${s.nome}</option>`).join(''); openModal('modal-user'); }
function editUser(id) { const u = usuarios.find(u=>u.id===id); if(!u) return; editingUserId = id; document.getElementById('user-modal-title').innerText = 'Editar Usuário'; document.getElementById('user-nome').value = u.nomeExibicao || u.nome; document.getElementById('user-login').value = u.nome; document.getElementById('user-senha').value = ''; document.getElementById('user-iniciais').value = u.iniciais || ''; document.getElementById('user-setor').innerHTML = setores.map(s => `<option value="${s.id}" ${s.id===u.setorId ? 'selected' : ''}>${s.nome}</option>`).join(''); openModal('modal-user'); }
function saveUser() { const nomeExibicao = document.getElementById('user-nome').value.trim(); const login = document.getElementById('user-login').value.trim(); const senha = document.getElementById('user-senha').value.trim(); const setorId = parseInt(document.getElementById('user-setor').value); const iniciais = document.getElementById('user-iniciais').value.trim().toUpperCase(); if(!nomeExibicao || !login) { alert('Preencha nome e login'); return; } if(editingUserId === null && !senha) { alert('Informe a senha para novo usuário'); return; } if(editingUserId === null) { const novoId = usuarios.length > 0 ? Math.max(...usuarios.map(u=>u.id)) + 1 : 1; usuarios.push({ id:novoId, nome:login, senha:senha, setorId, nomeExibicao, iniciais:iniciais||nomeExibicao.substring(0,2).toUpperCase() }); showToast('Usuário criado'); } else { const u = usuarios.find(u=>u.id===editingUserId); if(u) { u.nome = login; if(senha) u.senha = senha; u.setorId = setorId; u.nomeExibicao = nomeExibicao; u.iniciais = iniciais || nomeExibicao.substring(0,2).toUpperCase(); showToast('Usuário atualizado'); } } closeModal('modal-user'); renderAdminUsers(); salvarDados(); }
function deleteUser(id) { if(id === 1) { alert('Não é possível excluir o administrador principal.'); return; } if(confirm('Excluir este usuário?')) { usuarios = usuarios.filter(u => u.id !== id); renderAdminUsers(); salvarDados(); showToast('Usuário removido'); } }

let editingSetorId = null;
function openNewSetorModal() { editingSetorId = null; document.getElementById('setor-modal-title').innerText = 'Novo Setor'; document.getElementById('setor-nome').value = ''; const todasPermissoes = ['dashboard','kanban','processos','clientes','agenda','relatorios','admin','publicacoes']; document.getElementById('setor-permissoes-list').innerHTML = todasPermissoes.map(perm => `<label class="perm-checkbox"><input type="checkbox" value="${perm}"> ${perm}</label>`).join(''); openModal('modal-setor'); }
function editSetor(id) { const s = setores.find(s=>s.id===id); if(!s) return; editingSetorId = id; document.getElementById('setor-modal-title').innerText = 'Editar Setor'; document.getElementById('setor-nome').value = s.nome; const todasPermissoes = ['dashboard','kanban','processos','clientes','agenda','relatorios','admin','publicacoes']; document.getElementById('setor-permissoes-list').innerHTML = todasPermissoes.map(perm => `<label class="perm-checkbox"><input type="checkbox" value="${perm}" ${s.permissoes.includes(perm) ? 'checked' : ''}> ${perm}</label>`).join(''); openModal('modal-setor'); }
function saveSetor() { const nome = document.getElementById('setor-nome').value.trim(); if(!nome) { alert('Nome do setor é obrigatório'); return; } const checkboxes = document.querySelectorAll('#setor-permissoes-list input[type="checkbox"]'); const permissoes = Array.from(checkboxes).filter(cb => cb.checked).map(cb => cb.value); if(editingSetorId === null) { const novoId = setores.length > 0 ? Math.max(...setores.map(s=>s.id)) + 1 : 1; setores.push({ id:novoId, nome, permissoes }); showToast('Setor criado'); } else { const s = setores.find(s=>s.id===editingSetorId); if(s) { s.nome = nome; s.permissoes = permissoes; showToast('Setor atualizado'); } } closeModal('modal-setor'); renderAdminSetores(); renderAdminUsers(); carregarSetoresNoSelectPermissao(); salvarDados(); }
function deleteSetor(id) { if(id === 1 || id === 2 || id === 3 || id === 4) { alert('Não é possível excluir setores padrão do sistema.'); return; } if(confirm('Excluir este setor?')) { setores = setores.filter(s => s.id !== id); renderAdminSetores(); renderAdminUsers(); carregarSetoresNoSelectPermissao(); salvarDados(); showToast('Setor removido'); } }

document.addEventListener('click', function(e) { if(e.target.classList && e.target.classList.contains('admin-tab')) { document.querySelectorAll('.admin-tab').forEach(tab => tab.classList.remove('active')); e.target.classList.add('active'); const tabId = e.target.getAttribute('data-tab'); document.querySelectorAll('.admin-panel').forEach(panel => panel.style.display = 'none'); if(tabId === 'users') document.getElementById('admin-users-panel').style.display = 'block'; if(tabId === 'setores') { document.getElementById('admin-setores-panel').style.display = 'block'; renderAdminSetores(); } if(tabId === 'permissoes') { document.getElementById('admin-permissoes-panel').style.display = 'block'; carregarPermissoesDoSetor(); } if(tabId === 'oab') { document.getElementById('admin-oab-panel').style.display = 'block'; adminRenderOabList(); adminCarregarConfigPub(); renderAdminLog(); } } });

function toggleNotif(){ const p=document.getElementById('notif-panel'); p.style.display=p.style.display==='flex'?'none':'flex'; renderNotifs(); }
function renderNotifs() { document.getElementById('notif-list').innerHTML = notifications.map(n=>`<div style="padding:8px;border-bottom:1px solid var(--border);"><strong>${n.from}</strong><div>${n.text}</div><small>${n.time}</small></div>`).join(''); }
function updateNotifBadge() { const unread = notifications.filter(n=>n.unread).length; document.getElementById('notif-count').textContent = unread || ''; }
